#ifndef __GBEmuGUIMainWindow__
#define __GBEmuGUIMainWindow__

/**
@file
Subclass of MainWindow, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing MainWindow */
class GBEmuGUIMainWindow : public MainWindow
{
	protected:
		// Handlers for MainWindow events.
		void OnExit( wxCommandEvent& event );
	public:
		/** Constructor */
		GBEmuGUIMainWindow( wxWindow* parent );
	//// end generated class members
	
};

#endif // __GBEmuGUIMainWindow__
